### ISSUE TITLE
Exposure of project secrets

### ISSUE THREAD

**Issue by merzainc** [paynow/Paynow-NodeJS-SDK#29]
**I'm really concerned about the secrets of the project being exposed to everyone.**
After attempting to read the Paynow NodeJS codebase so that I can collaborate if needed. I saw that in the root folder of the SDK project, secrets e.g api_key
![Screenshot_20230130_160337](https://user-images.githubusercontent.com/114744793/215502439-fd7a86e8-611a-4435-ba01-2e17c3eb74c7.png)
 were being exposed to the public. Would you mind confirming whether this is necessary and why? I have attached a screenshot from the travis.yml file.

**Comment by iammerus** [comment]
@merzainc  AFAIK, This does not leak the API key for the project. The api_key field in the travis-ci config is encrypted with a public key that is specific to this repository. Only Travis CI can decrypt it with the corresponding private key, and it will use it to authenticate with npm when deploying the package.

**Comment by merzainc** [comment]
> 

Thank you for the clarification.
