### ISSUE TITLE
What is the versioning policy

### ISSUE THREAD

**Issue by michaeldera** [paynow/Paynow-NodeJS-SDK#4]
So if I want to make changes to the SDK that would change some of the changes that would affect the way the SDK work, what is the policy for going about that?

Is it possible to have a separate branch for development of a version that can affect how the current one is working?

**Comment by webdevprojects-zw** [comment]
Hey @michaeldera. We've taken forever to respond to this (sorry!) but we've now created a `develop` branch that you can contribute to and that can be later merged into `master` when changes are stable and ready.

**Comment by webdevprojects-zw** [comment]
Hey @michaeldera. We've taken forever to respond to this (sorry!) but we've now created a `develop` branch that you can contribute to and that can be later merged into `master` when changes are stable and ready.

**Comment by michaeldera** [comment]
Okay thank you. Will work from that branch.
