### ISSUE TITLE
Confirm payment made

### ISSUE THREAD

**Issue by lovelovelovelovelovelovelove** [paynow/Paynow-NodeJS-SDK#7]
I am struggling to find a way to confirm when payment for mobile has been initiated, pollUrl returns undefined, How can I confirm when payment has been cancelled, or was successful  for MOBILE

**Comment by Lesruez93** [comment]
Yes Same here

**Comment by melmups** [comment]
Hi @lovelovelovelovelovelovelove. Can you please post a sample of your initialization code?

**Comment by lovelovelovelovelovelovelove** [comment]
app.post('/api/pay/:amount/:title/:number/:referrence',(req,res) => {


	let amnt = parseFloat(req.params.amount)
	// Create a new payment
	let payment = paynow.createPayment(req.params.title,'anelesiwawa@outlook.com');
	payment.add(req.params.title, amnt);

	

	// Set return and result urls
	// Set return and result urls
	paynow.resultUrl = "https://eventit.co.zw/event/I5uPZUa7UOfma2EbmKTg";
	paynow.returnUrl = "https://eventit.co.zw/event/I5uPZUa7UOfma2EbmKTg";


	var number = req.params.number;
	console.log(`We are in, number is ${number}`);
	console.log(`We are in, fee is ${amnt}`);

	paynow.sendMobile( 
    
		    // The payment to send to Paynow
		    payment, 

		    // The phone number making payment
		    number
		    //'0771111111'
		    ,
		    
		    // The mobile money method to use. 
		    'ecocash' 

		).then((response) => {
		    if(response.success) {
		        // These are the instructions to show the user. 
		        // Instruction for how the user can make payment
		        let instructions = response.instructions 
		        // Get Payment instructions for the selected mobile money method


		        // Get poll url for the transaction.This is the url used to check the status of the transaction. 
		        // You might want to save this, we recommend you do it
                       
                      // Trying to get poll url
                      let pollUrl = response.pollUrl;
                     console.log(pollUrl)
                      // So I can see if pollURL was part of the response, it wasn't                    
                       console.log(JSON.stringify(response))


								

				
		        

		    } else {
		        console.log("There was an error, " + response.error)
		        res.send("Error");
		    }
		}).catch(ex => {
		    // Ahhhhhhhhhhhhhhh
		    // *freak out*
		    console.log('Your application has broken an axle ERROR ', ex)
		    res.send("Error");
		});


	




});

**Comment by melmups** [comment]
Hi @lovelovelovelovelovelovelove. This issue has been resolved in commit [00a4fce](https://github.com/paynow/Paynow-NodeJS-SDK/commit/00a4fcec4a0f590fbc761ea9d1c7b69f67682805)

**Comment by lovelovelovelovelovelovelove** [comment]
Thank you!
